sudo: true
language: java
dist: trusty
group: edge
jdk: 
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - DISPLAY=:99.0
before_install:
  - sh -e /etc/init.d/xvfb start - sleep 10
script:
  - set -e
  - cd org.genivi.commonapi.core.releng
  - mvn -Dtarget.id=org.genivi.commonapi.core.target clean verify
 
